Project113_G3/Models/UserData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project113_G3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserData
{

    public int UID { get; set; }

    public string Name { get; set; }

    public string Email_User { get; set; }

    public Nullable<System.DateTime> Bd_User { get; set; }

    public string GenderUser { get; set; }

    public string Description { get; set; }

    public string User_Id { get; set; }

    public string url { get; set; }

    public Nullable<System.DateTime> JoinDate { get; set; }

}

}

Project113_G3/Controllers/UserDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project113_G3.Models;

namespace Project113_G3.Controllers
{
    public class UserDatasController : Controller
    {
        private UserDataAccEntities db = new UserDataAccEntities();

        // GET: UserDatas
        public ActionResult Index()
        {
            var userDatas = db.UserDatas.Include(u => u.Email_User);
            return View(userDatas.ToList());
        }

        // GET: UserDatas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserData userData = db.UserDatas.Find(id);
            if (userData == null)
            {
                return HttpNotFound();
            }
            return View(userData);
        }

        // GET: UserDatas/Create
        public ActionResult Create()
        {
            ViewBag.User_Id = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: UserDatas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UID,Name,Email_User,Bd_User,GenderUser,Description,User_Id,url,JoinDate")] UserData userData)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    userData.url = fileName;
                }

                userData.JoinDate = DateTime.Now;

                db.UserDatas.Add(userData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User_Id = new SelectList(db.AspNetUsers, "Id", "Email", userData.User_Id);
            return View(userData);
        }

        // GET: UserDatas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserData userData = db.UserDatas.Find(id);
            if (userData == null)
            {
                return HttpNotFound();
            }
            ViewBag.User_Id = new SelectList(db.AspNetUsers, "Id", "Email", userData.User_Id);
            return View(userData);
        }

        // POST: UserDatas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UID,Name,Email_User,Bd_User,GenderUser,Description,User_Id,url,JoinDate")] UserData userData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User_Id = new SelectList(db.AspNetUsers, "Id", "Email", userData.User_Id);
            return View(userData);
        }

        // GET: UserDatas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserData userData = db.UserDatas.Find(id);
            if (userData == null)
            {
                return HttpNotFound();
            }
            return View(userData);
        }

        // POST: UserDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserData userData = db.UserDatas.Find(id);
            db.UserDatas.Remove(userData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project113_G3/Views/UserDatas/Create.cshtml
@model Project113_G3.Models.UserData

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "UserDatas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            &nbsp;
            <h2>UserData</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Bd_User, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bd_User, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bd_User, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GenderUser, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GenderUser, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GenderUser, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.HiddenFor(model => model.JoinDate)

            <div class="form-group">
                @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control", Type = "file" } })
                    @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Project113_G3/Views/UserDatas/Delete.cshtml
@model Project113_G3.Models.UserData

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>UserData</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email_User)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email_User)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Bd_User)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Bd_User)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GenderUser)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GenderUser)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.url)
            </dt>

            <dd>
                <img src=@Url.Content("~/Content/images/" +(Model.url)) style="width:100px ; height:auto" />
                @Html.DisplayFor(model => model.url)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.JoinDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.JoinDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Project113_G3/Views/UserDatas/Details.cshtml
@model Project113_G3.Models.UserData

@{
    Layout = null;
}

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>UserData</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.UID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AspNetUser.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Bd_User)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Bd_User)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GenderUser)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GenderUser)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.JoinDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.JoinDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.url)
            </dt>

            <dd>
                <img src=@Url.Content("~/Content/images/" +(Model.url)) style="width:100px ; height:auto" />
                @Html.DisplayFor(model => model.url)
            </dd>



        </dl>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Project113_G3/Views/UserDatas/Edit.cshtml
@model Project113_G3.Models.UserData

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>UserData</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email_User, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email_User, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email_User, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Bd_User, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bd_User, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bd_User, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.GenderUser, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GenderUser, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GenderUser, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.User_Id, "User_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("User_Id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.JoinDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.JoinDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Project113_G3/Views/UserDatas/Index.cshtml
@model IEnumerable<Project113_G3.Models.UserData>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mitr">
    <link rel="stylesheet" type="text/css" href="~/Content/css/Dashboard_css.css">

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <title>หลังบ้าน</title>
</head>
<body>

    <input type="checkbox" id="check" />
    <label for="check">
        <i class="fa fa-bars" id="okbuttom">
            <ion-icon name="menu-outline"></ion-icon>
        </i>

        <i class="fa fa-time" id="cancelbuttom">
            <ion-icon name="close-outline"></ion-icon>
        </i>

    </label>

    <div class="navigation">
        <ul>
            <content>FPTP</content>
            <li>
                <a href="#">
                    <span class="UserAcc">ชื่อสมาชิก</span>
                </a>
            </li>
            <li>
                <a href="~/Dashboard/Index">
                    <span class="icon"><ion-icon name="home-outline"></ion-icon></span>
                    <span class="title">Home</span>
                </a>
            </li>

            <li>
                <a href="~/DataGames/Index">
                    <span class="icon"><ion-icon name="game-controller-outline"></ion-icon></span>
                    <span class="title">System Information</span>
                </a>
            </li>

            <li>
                <a href="~/UserDatas/Index">
                    <span class="icon"><ion-icon name="person-outline"></ion-icon></span>
                    <span class="title">Account</span>
                </a>
            </li>

            <li>
                <a href="#">
                    <span class="icon"><ion-icon name="reader-outline"></ion-icon></span>
                    <span class="title">Reporting</span>
                </a>
            </li>

            <li>
                <a href="#">
                    <span class="icon"><ion-icon name="git-pull-request-outline"></ion-icon></span>
                    <span class="title">Request</span>
                </a>
            </li>

            <li>
                @Html.Partial("_LoginPartial")
            </li>
        </ul>
    </div>

    <!--ที่ปิดเมนู / ช่องค้นหา / โปรไฟล์ Admin-->
    <div class="main">
        <div class="topbar">
            <div class="Namepage">
                <h3>Account User</h3>
            </div>

            <div class="search">
                <input type="text" placeholder="Search here!" />
                <ion-icon name="search-outline"></ion-icon>
            </div>

            <div class="accountPic">
                <img src="~/Content/images/SH2.jpg" />
            </div>
        </div>


        <!-- กรอบข้อมูลกราฟ-->
        <div class="details">
            <div class="graph">
                <div class="cardHeader" name="cardGraph">

                    <p>
                        @Html.ActionLink("Create New", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.UID)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AspNetUser.Email)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Bd_User)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.GenderUser)
                            </th>


                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UID)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.AspNetUser.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Bd_User)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GenderUser)
                                </td>


                                <td>
                                    @Html.ActionLink("Details", "Details", new { id = item.UID }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.UID })
                                </td>
                            </tr>
                        }

                    </table>

                </div>

            </div>
        </div>

    </div>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>